// Package model contains data structures and business logic for the Library Management System.
// This package defines all entity models with proper validation tags and provides
// getter/setter methods following encapsulation principles. Each model file
// corresponds to a database table and includes constructor functions and
// business logic methods specific to that entity.
package model

// Student represents a student entity in the library management system.
// This struct maps to the 'students' table in the database and includes
// validation tags for automatic request validation when used with Gin binding.
//
// Database Table: students
// Fields:
//   - ID: Auto-increment primary key
//   - Name: Student's full name (required)
//   - Email: Unique email address with email validation (required)
//   - Phone: 10-digit phone number with numeric validation (required)
//   - Password: Hashed password for authentication (required)
//
// JSON Tags: Used for API request/response serialization
// Binding Tags: Used by Gin framework for automatic validation
// GORM Tags: Used by GORM for database schema generation and constraints
type Student struct {
	ID       uint   `json:"id" gorm:"primaryKey;autoIncrement"`                                           // Primary key, auto-generated by database
	Name     string `json:"name" binding:"required" gorm:"type:varchar(100);not null"`                    // Full name, cannot be empty
	Email    string `json:"email" binding:"required,email" gorm:"type:varchar(100);uniqueIndex;not null"` // Must be valid and unique
	Phone    string `json:"phone" binding:"required,len=10,numeric" gorm:"type:varchar(10);not null"`     // Exactly 10 digits
	Password string `json:"password" binding:"required" gorm:"type:varchar(255);not null"`                // Hashed password for storage
}

// NewStudent creates and returns a new Student instance with the provided details.
// This constructor function initializes a Student struct with the given parameters.
// The ID field is left as zero and will be set by the database when the record is inserted.
//
// Parameters:
//   - name: The student's full name
//   - email: The student's email address (should be unique)
//   - phone: The student's 10-digit phone number
//   - password: The student's plain text password (will be hashed before storage)
//
// Returns:
//   - *Student: Pointer to the newly created Student instance
//
// Usage:
//
//	student := NewStudent("John Doe", "john@example.com", "1234567890", "password123")
func NewStudent(name, email, phone, password string) *Student {
	return &Student{
		Name:     name,
		Email:    email,
		Phone:    phone,
		Password: password,
		// ID is omitted and will be set by database auto-increment
	}
}

// GetID returns the student's unique identifier.
// This ID is typically assigned by the database when the student record is created.
func (s *Student) GetID() uint {
	return s.ID
}

// SetID sets the student's unique identifier.
// This method is typically used after retrieving a record from the database
// or when the database assigns an ID after insertion.
func (s *Student) SetID(id uint) {
	s.ID = id
}

// GetName returns the student's full name.
func (s *Student) GetName() string {
	return s.Name
}

// SetName sets the student's full name.
func (s *Student) SetName(name string) {
	s.Name = name
}

// GetEmail returns the student's email address.
func (s *Student) GetEmail() string {
	return s.Email
}

// SetEmail sets the student's email address.
// Note: Email should be unique in the database.
func (s *Student) SetEmail(email string) {
	s.Email = email
}

// GetPhone returns the student's phone number.
func (s *Student) GetPhone() string {
	return s.Phone
}

// SetPhone sets the student's phone number.
// Should be a 10-digit numeric string.
func (s *Student) SetPhone(phone string) {
	s.Phone = phone
}

// GetPassword returns the student's password.
// Note: This may be either plain text (during input) or hashed (when stored).
func (s *Student) GetPassword() string {
	return s.Password
}

// SetPassword sets the student's password.
// Warning: Ensure password is hashed before calling this method for storage.
func (s *Student) SetPassword(password string) {
	s.Password = password
}
